CUDA_VISIBLE_DEVICES=0,1 nohup python -u __main_completion__.py \
        --model_type beta \
        --layers 5 \
        --e_ff_fold 2 \
        --attn_heads 8 \
        --hidden 1024 \
        --lan_embedding_dim 512 \
        --projection_dim 512 \
        --batch_size 64 \
        --accu_batch_size 128 \
        --val_batch_size 256 \
        --infer_batch_size 256 \
        --lr 1e-4 \
        --min_lr 1e-6 \
        --MultiStepLR True \
        --milestones 30 35 \
        --lr_scheduler True > nohup.log 2>&1 &
